name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
autolabeler:
  - label: chore
    files:
      - "*.md"
    title:
      - "/docs/i"
      - "/chore/i"
  - label: bug
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: enhancement
    title:
      - "/feat/i"
  - label: breaking
    title:
      - "/fix!/i"
      - "/feat!/i"
      - "/refactor!/i"
    body:
      - "/breaking change/i"
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bug
  - title: 🧰 Maintenance
    labels:
      - chore
      - docs
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - skip-changelog
  - chore
version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
      - fix
  default: patch
template: |
  ## Changes

  $CHANGES
