name: Label PR

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
