name: Go Test on PR

on:
  pull_request_target:
    paths:
      - "*/**"
      - "*.go"
      - go.*
      - "!.github/**"
      - "!tmp/**"

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Checkout current
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge PR into current
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Test
        run: go test -json ./... > test.json
        env:
          GOPRIVATE: github.com/inquisico

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json
