name: Go Lint on Push
on:
  push:
    branches:
      - master
    paths:
      - "*/**"
      - "*.go"
      - go.*
      - "!.github/**"
      - "!tmp/**"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache: false # disable cache to avoid conflicts with golangci

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
