name: Go Lint on Push
on:
  push:
    branches:
      - master
    paths:
      - "*/**"
      - go.*
      - "!.github/**"
      - "!dev/**"
      - "!tmp/**"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache: false # disable cache to avoid conflicts with golangci

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=10m
